<a href="https://colab.research.google.com/github/son50git/LIVE_002_Human_Pose/blob/master/PKT_001_Rework_03.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [29]:
from __future__ import print_function  
# for Python2 compatibility

In [30]:
import numpy 
numpy.random.seed(1337)   # for experiment reproducibility

In [31]:
import keras
from keras.models import Sequential
from keras.layers import Dense 
from keras.optimizers import SGD 
from keras.datasets import mnist

In [32]:
num_classes = 10
batch_size = 128     
epochs = 20

In [33]:
# the data, shuffled and split between train and test sets
(x_train, y_train), (x_test, y_test) = mnist.load_data()

In [34]:
print(type(x_train))
print(x_train.shape)
print(type(y_train))
print(y_train.shape)

print(type(x_test))
print(x_test.shape)
print(type(y_test))
print(y_test.shape)

<class 'numpy.ndarray'>
(60000, 28, 28)
<class 'numpy.ndarray'>
(60000,)
<class 'numpy.ndarray'>
(10000, 28, 28)
<class 'numpy.ndarray'>
(10000,)


In [35]:
x_train[0:3]

array([[[0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0],
        ...,
        [0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0]],

       [[0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0],
        ...,
        [0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0]],

       [[0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0],
        ...,
        [0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0]]], dtype=uint8)

In [36]:
x_train = x_train.reshape(60000, 784)  # 28x28 = 784
x_test = x_test.reshape(10000, 784)

x_train = x_train.astype('float32') 
x_test = x_test.astype('float32') 

x_train /= 255  # 0 - 255 ...  0-1 
x_test /= 255   # normalizing your data 

print(x_train[0])

[0.         0.         0.         0.         0.         0.
 0.         0.         0.         0.         0.         0.
 0.         0.         0.         0.         0.         0.
 0.         0.         0.         0.         0.         0.
 0.         0.         0.         0.         0.         0.
 0.         0.         0.         0.         0.         0.
 0.         0.         0.         0.         0.         0.
 0.         0.         0.         0.         0.         0.
 0.         0.         0.         0.         0.         0.
 0.         0.         0.         0.         0.         0.
 0.         0.         0.         0.         0.         0.
 0.         0.         0.         0.         0.         0.
 0.         0.         0.         0.         0.         0.
 0.         0.         0.         0.         0.         0.
 0.         0.         0.         0.         0.         0.
 0.         0.         0.         0.         0.         0.
 0.         0.         0.         0.         0.         

In [37]:
print(x_train.shape)
print(y_train.shape)

(60000, 784)
(60000,)


In [38]:
print(y_train[0])
y_train[0:10]

5


array([5, 0, 4, 1, 9, 2, 1, 3, 1, 4], dtype=uint8)

In [39]:
# convert class vectors to binary class matrices
y_train2 = keras.utils.to_categorical(y_train, num_classes)
y_test2 = keras.utils.to_categorical(y_test, num_classes)

In [40]:
y_train2[0:10] # one-hot vector

array([[0., 0., 0., 0., 0., 1., 0., 0., 0., 0.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [0., 0., 1., 0., 0., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0., 0., 0., 0.]], dtype=float32)

In [41]:
y_train = y_train2
y_test = y_test2

In [42]:
model = Sequential()
model.add( Dense(512, activation='sigmoid', input_shape=(784,)  ) )
model.add( Dense(512, activation='sigmoid'  ) )
model.add( Dense(num_classes, activation='softmax'))

In [43]:
model.summary()

Model: "sequential_1"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
dense_3 (Dense)              (None, 512)               401920    
_________________________________________________________________
dense_4 (Dense)              (None, 512)               262656    
_________________________________________________________________
dense_5 (Dense)              (None, 10)                5130      
Total params: 669,706
Trainable params: 669,706
Non-trainable params: 0
_________________________________________________________________


In [44]:
# Compile the model 
model.compile(loss='categorical_crossentropy', optimizer=SGD(), 
              metrics=['accuracy'])

In [45]:
# let's perform the learning 
history = model.fit( x_train, y_train, 
           batch_size=batch_size,
           epochs=epochs, 
           verbose=1, 
           validation_data=(x_test, y_test))

Epoch 1/20
469/469 [==============================] - 6s 13ms/step - loss: 2.2652 - accuracy: 0.2118 - val_loss: 2.2230 - val_accuracy: 0.3242
Epoch 2/20
469/469 [==============================] - 6s 12ms/step - loss: 2.1832 - accuracy: 0.4008 - val_loss: 2.1319 - val_accuracy: 0.5642
Epoch 3/20
469/469 [==============================] - 6s 13ms/step - loss: 2.0751 - accuracy: 0.5360 - val_loss: 2.0006 - val_accuracy: 0.5880
Epoch 4/20
469/469 [==============================] - 6s 13ms/step - loss: 1.9148 - accuracy: 0.6114 - val_loss: 1.8032 - val_accuracy: 0.6736
Epoch 5/20
469/469 [==============================] - 6s 13ms/step - loss: 1.6932 - accuracy: 0.6661 - val_loss: 1.5553 - val_accuracy: 0.7049
Epoch 6/20
469/469 [==============================] - 6s 13ms/step - loss: 1.4429 - accuracy: 0.7120 - val_loss: 1.3077 - val_accuracy: 0.7373
Epoch 7/20
469/469 [==============================] - 6s 13ms/step - loss: 1.2193 - accuracy: 0.7497 - val_loss: 1.1073 - val_accuracy: 0.7757

In [46]:
# Let's evaluate the model 
score = model.evaluate(x_test, y_test)

313/313 [==============================] - 1s 3ms/step - loss: 0.4455 - accuracy: 0.8787


In [48]:
score = model.evaluate(x_test, y_test, verbose=0)
print('Test loss:', score[0])
print('Test accuracy:', score[1])

Test loss: 0.4454677104949951
Test accuracy: 0.8787000179290771
